@echo off
echo Starting EnergyScope Application...
echo.
echo Starting Backend...
start cmd /k "cd backend && mvnw spring-boot:run"
echo Waiting for backend to initialize...
timeout /t 15
echo.
echo Starting Frontend...
start cmd /k "cd frontend && npm start"
echo.
echo Application startup initiated. Please wait for both components to fully load.